
spring:
  h2.console:
    enabled: true
    path: '/console'

  datasource:
    url: 'jdbc:h2:file:/C:/Users/Ja/IdeaProjects/MigracjeFlyway/produkty.db'
    driverClassName: 'org.h2.Driver'
    username: 'sa'

  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
    hibernate:
      ddl-auto: validate
